#pragma once

//From glfw3.h
#define CRYSTAL_MOUSE_BUTTON_1         0
#define CRYSTAL_MOUSE_BUTTON_2         1
#define CRYSTAL_MOUSE_BUTTON_3         2
#define CRYSTAL_MOUSE_BUTTON_4         3
#define CRYSTAL_MOUSE_BUTTON_5         4
#define CRYSTAL_MOUSE_BUTTON_6         5
#define CRYSTAL_MOUSE_BUTTON_7         6
#define CRYSTAL_MOUSE_BUTTON_8         7
#define CRYSTAL_MOUSE_BUTTON_LAST      CRYSTAL_MOUSE_BUTTON_8
#define CRYSTAL_MOUSE_BUTTON_LEFT      CRYSTAL_MOUSE_BUTTON_1
#define CRYSTAL_MOUSE_BUTTON_RIGHT     CRYSTAL_MOUSE_BUTTON_2
#define CRYSTAL_MOUSE_BUTTON_MIDDLE    CRYSTAL_MOUSE_BUTTON_3